### PR TITLE
logging bug fix

### PR DESCRIPTION
**Pull request by shashank-boyapally**
## Type of change

- [ ] Refactor
- [ ] New feature
- [x] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description
duplicate logs were being generated when multiple matcher class objects were being created. Added some more context to the logs.

## Related Tickets & Documents

- Related Issue #21 
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by paigerube14** [comment]
@shashank-boyapally do you have any example logs of before and after the fix?

**Comment by shashank-boyapally** [comment]
Hi @paigerube14, please find the example logs below, the before shows when 7th request was made in daemon-mode of orion, hence duplicating 7 times.
Before
```
2024-03-21 10:23:42,084 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,084 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,084 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,084 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,084 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,084 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,084 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,167 - Orion - INFO - file: utils.py - line: 262 - The test aws-small-scale-cluster-density-v2 has started
2024-03-21 10:23:42,168 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,168 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,168 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,168 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,168 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,168 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,168 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,199 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,199 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,199 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,199 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,199 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,199 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,199 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:23:42,227 - Matcher - INFO - Executing query against index=ripsaw-kube-burner*
2024-03-21 10:23:42,227 - Matcher - INFO - Executing query against index=ripsaw-kube-burner*
2024-03-21 10:23:42,227 - Matcher - INFO - Executing query against index=ripsaw-kube-burner*
2024-03-21 10:23:42,227 - Matcher - INFO - Executing query against index=ripsaw-kube-burner*
2024-03-21 10:23:42,227 - Matcher - INFO - Executing query against index=ripsaw-kube-burner*
2024-03-21 10:23:42,227 - Matcher - INFO - Executing query against index=ripsaw-kube-burner*
2024-03-21 10:23:42,227 - Matcher - INFO - Executing query against index=ripsaw-kube-burner*
2024-03-21 10:23:42,262 - Orion - INFO - file: utils.py - line: 125 - Collecting podReadyLatency
2024-03-21 10:23:42,262 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:42,262 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:42,262 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:42,262 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:42,262 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:42,262 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:42,262 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:42,297 - Orion - INFO - file: utils.py - line: 125 - Collecting apiserverCPU
2024-03-21 10:23:42,298 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:42,298 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:42,298 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:42,298 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:42,298 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:42,298 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:42,298 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:43,163 - Orion - INFO - file: utils.py - line: 125 - Collecting ovnCPU
2024-03-21 10:23:43,163 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:43,163 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:43,163 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:43,163 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:43,163 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:43,163 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:43,163 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:44,562 - Orion - INFO - file: utils.py - line: 125 - Collecting etcdCPU
2024-03-21 10:23:44,562 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:44,562 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:44,562 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:44,562 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:44,562 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:44,562 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:23:44,562 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
```

After
```
2024-03-21 10:37:52,021 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:37:52,152 - Orion - INFO - file: utils.py - line: 262 - The test aws-small-scale-cluster-density-v2 has started
2024-03-21 10:37:52,153 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:37:52,190 - Matcher - INFO - Executing query against index=perf_scale_ci
2024-03-21 10:37:52,220 - Matcher - INFO - Executing query against index=ripsaw-kube-burner*
2024-03-21 10:37:52,361 - Orion - INFO - file: utils.py - line: 125 - Collecting podReadyLatency
2024-03-21 10:37:52,361 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:37:52,482 - Orion - INFO - file: utils.py - line: 125 - Collecting apiserverCPU
2024-03-21 10:37:52,483 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:37:53,781 - Orion - INFO - file: utils.py - line: 125 - Collecting ovnCPU
2024-03-21 10:37:53,781 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
2024-03-21 10:37:55,527 - Orion - INFO - file: utils.py - line: 125 - Collecting etcdCPU
2024-03-21 10:37:55,527 - Matcher - INFO - Executing query against index=ripsaw-kube-burner
```

**Review by paigerube14 — APPROVED** [review]
/lgtm

**Review by vishnuchalla — CHANGES_REQUESTED** [review]
Might need this implementation as suggested here: https://github.com/cloud-bulldozer/orion/pull/26#discussion_r1537446809

**Comment by shashank-boyapally** [comment]
closing since #26 is covering this.

**Pull request closed without merging**
